version: "3.7"
services:
  airflow:
    build: ../../docker
    image: localhost/mi-airflow:latest
    ports:
      - "8080:8080"
    networks:
      - airflow
    volumes:
      - ./dags:/root/airflow/dags
  postgres:
    build: insideairbnb
    ports:
      - "8080:8080"
    networks:
      - airflow
    volumes:
      - ./dags:/root/airflow/dags

networks:
  airflow:
