name: CI

on: [push]
#  push:
#    paths:
#      - "*.py"

jobs:
  precommit:
    name: Pre-commit
    runs-on: ubuntu-23.10
    steps:
      - uses: actions/checkout@v1 # 
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all
